_REGION=asia-southeast1
_SERVICE=event-management-api
_ARTIFACT_REPO=app
_FE_BUCKET=web-frontend-1
_FE_DIR=frontend
_BE_DIR=backend
_IMAGE=asia-southeast1-docker.pkg.dev/event-management-prod-474206/app/event-management-api:$SHORT_SHA
_VPC_CONNECTOR=serverless-vpc-as1
_SQL_INSTANCE=projects/event-management-prod-474206/locations/asia-southeast1/instances/eventmanagement
_MAX_INSTANCES=10
_MIN_INSTANCES=2
